# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEntry',
            fields=[
                ('domainID', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FAQAppClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentQuestions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionAsked', models.CharField(max_length=250)),
                ('questionScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUrlMapping',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=250)),
                ('serviceFilePath', models.CharField(max_length=250)),
                ('domainID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskFAQApp.DomainEntry')),
            ],
        ),
    ]
