# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskFAQApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceurlmapping',
            name='serviceCrawlerUrl',
            field=models.CharField(default='dummyUrl', max_length=250),
        ),
    ]
